version: '3.8'

services:
  brida-db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: brida-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: edaily_prod
      POSTGRES_USER: edaily_user
      POSTGRES_PASSWORD: "Persibnuaing1933!"
    volumes:
      - brida_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - brida-network

  brida-be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brida-be
    restart: unless-stopped
    depends_on:
      - brida-db
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      PORT: 3000
      NODE_ENV: production
      DATABASE_URL: "postgresql://edaily_user:Persibnuaing1933!@brida-db:5432/edaily_prod?schema=public"
    networks:
      - brida-network
      - e-daily-report_default

networks:
  brida-network:
  e-daily-report_default:
    external: true

volumes:
  brida_db_data:
